# Generated by Django 5.0.6 on 2024-06-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='phoneno',
            field=models.CharField(max_length=12),
        ),
    ]
