# Generated by Django 5.0.6 on 2024-06-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0002_alter_login_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('Qualification', models.TextField()),
                ('salary', models.IntegerField()),
                ('_id', models.CharField(max_length=255)),
            ],
        ),
    ]
