# Generated by Django 5.0.6 on 2024-06-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0003_add_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_job',
            name='companyName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
