# Generated by Django 5.0.6 on 2024-06-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0004_add_job_companyname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_job',
            name='_id',
        ),
    ]
