# Generated by Django 5.0.6 on 2024-06-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0006_add_job_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_job',
            name='_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
