# Generated by Django 5.0.6 on 2024-06-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0008_remove_add_job__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_job',
            name='_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
