# Generated by Django 5.0.6 on 2024-06-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0009_add_job__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_job',
            name='_id',
        ),
    ]
