# Generated by Django 5.0.6 on 2024-07-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0012_save_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save_jobs',
            old_name='saved_jobs',
            new_name='jobs',
        ),
    ]
