# Generated by Django 5.0.6 on 2024-07-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0013_rename_saved_jobs_save_jobs_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_profile_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='', verbose_name='document/')),
            ],
        ),
    ]
