# Generated by Django 5.0.6 on 2024-07-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0014_add_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_profile_photo',
            name='photo',
            field=models.FileField(upload_to='document/'),
        ),
    ]
