# Generated by Django 5.0.6 on 2024-07-26 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0015_alter_add_profile_photo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_application2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=200)),
                ('Years', models.CharField(max_length=20)),
                ('new_resume', models.FileField(upload_to='document/')),
                ('job_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job_portal_app.add_job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job_portal_app.add_resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
