# Generated by Django 5.0.6 on 2024-07-26 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0016_job_application2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_application2',
            old_name='Years',
            new_name='noofyears',
        ),
    ]
