# Generated by Django 5.0.6 on 2024-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0018_employer_applied_job_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higher_secondary', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='employer_applied_job_view',
        ),
    ]
