# Generated by Django 5.0.6 on 2024-08-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0020_employer_applied_job_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application2',
            name='phoneno',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
