# Generated by Django 5.0.6 on 2024-08-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0022_companyreviewes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='companyReviewes',
            new_name='companyDetails',
        ),
    ]
