# Generated by Django 5.0.6 on 2024-08-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0023_rename_companyreviewes_companydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='company_details',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
