# Generated by Django 5.0.6 on 2024-08-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0025_remove_companydetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='logo',
            field=models.TextField(),
        ),
    ]
