# Generated by Django 5.0.6 on 2024-08-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0026_alter_companydetails_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application2',
            name='user_details',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
