# Generated by Django 5.0.6 on 2024-08-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_portal_app', '0027_job_application2_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
